### ISSUE TITLE
Is this gem maintained (and going to be in the future)?

### ISSUE THREAD

**Issue by owst** [pennylane-hq/activerecord-adapter-redshift#12]
Hi!

Pinging @jlebray @tancredeb @tdeo @toommz as members of the pennylane-hq organisation.

Thanks for your work to create and for publishing this gem, however I want to query the status of it in terms of maintenance? 

I can see a handful of unmerged PRs and an open issue showing that this gem doesn't work for Rails 7.1.2 (#11) and furthermore that this gem isn't published to rubygems.org (I think the existing gem with the same name is less robust/correct than this one, so perhaps this one can supplant that one - I'm not sure of the process to achieve that, though)

Would you be open to a PR fixing #11, to merge the existing PRs, and to try and publish this gem to rubygems? 

Ideally, as mentioned in https://github.com/kwent/activerecord6-redshift-adapter/pull/15 there would be a single cross-version gem for an ActiveRecord Redshift adapter (that could use a version scheme following Rails' for example) - do you have any thoughts on that?

Thanks,
Owen.

**Comment by quentindemetz** [comment]
Hi Owen,

Thanks for the nudge. We're not using Rails 7.1 (yet!) so haven't been very diligent in getting these things fixed. I've merged the relevant PRs and implemented the mentioned fixes for Rails 7.1, 🤞🏻 things work well for you now.

I'll be happy to merge PRs as they come.

As an alternative to having tags which match the rails releases, I think we can try to publish one single gem with conditionals based on `ActiveRecord.version` - and let's see how long we can keep up with that? 🤷🏻 

With regards to publishing on rubygems.org, sure why not. Seems like others have tried that before...

<img width="659" alt="image" src="https://github.com/pennylane-hq/activerecord7-redshift-adapter/assets/2451971/794e0805-e5a2-46a1-8166-60b0fd8d3693">

**Comment by quentindemetz** [comment]
Gem is available as [activerecord7-redshift-adapter-pennylane](https://rubygems.org/gems/activerecord7-redshift-adapter-pennylane/) ✅

**Comment by owst** [comment]
Thanks @quentindemetz!

I'm working through some failures locally and will try to create a PR to support 7.1

I'm not sure naming the gem on rubygems by the current (most appreciated!) owners/maintainers is a good idea - but I'm also not sure how to go about ceding the name of the current (unmaintained/broken) published `activerecord7-redshift-adapter` [gem](https://rubygems.org/gems/activerecord7-redshift-adapter)

**Comment by quentindemetz** [comment]
I'll be happy to take over an existing name, but we need to get consent by the existing owners/maintainers, which I'm not sure will be that easy.

**Comment by quentindemetz** [comment]
Yes, this gem is now maintained and will be for the foreseeable future. Thanks @owst for the nudge!
