### ISSUE TITLE
No git tags since v1.0.0

### ISSUE THREAD

**Issue by nekketsuuu** [pennylane-hq/activerecord-adapter-redshift#29]
Hello! First, thanks for creating a gem for AR 7 with a public repository.

I noticed that tags for v1.0.1 and v1.0.2 haven't pushed yet to this repository even though the corresponding versions are released on rubygems.

- https://github.com/pennylane-hq/activerecord-adapter-redshift/releases
- https://rubygems.org/gems/activerecord7-redshift-adapter-pennylane/versions

Would you please push tags to this repository manually? Thanks in advance.

Tips: Releasing a new version using `rake release` pushes a corresponding tag to its remote repository automatically. https://bundler.io/guides/creating_gem.html#releasing-the-gem

**Comment by ckhall** [comment]
been 2 months since this issue was opened.  any updates?

**Comment by quentindemetz** [comment]
✅

**Comment by nekketsuuu** [comment]
Thanks!
